# Site settings
title: Aleksandar Kircanski
email: akircanski at google's mail service
description: > # this means to ignore newlines until "baseurl:"
  This is a personal web-page yay
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.example.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

