# Site settings
title: thoughts etc
email: akircanski at google's mail service
description: > # this means to ignore newlines until "baseurl:"
  personal web-log
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://akircanski.github.io/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from
  - jekyll-katex

